// ============================================================
// BitNetMini — 14×14 binary MNIST → 10-class digit recognizer
// Auto-generated by export_to_verilog.py
// Weights: FC1 ternary {-1,0,+1} | FC2 3-bit {-3..+3}
// Arithmetic: addition/subtraction + shifts only — no multipliers
//
// NOTE: Ports that were originally declared as unpacked arrays
// (e.g. "output wire signed [15:0] logit_out [0:9]") are not
// legal Verilog-2001 and are rejected by Yosys's default
// frontend, even though Verilator (SystemVerilog-aware) accepts
// them. Those ports have been flattened into single packed
// buses (e.g. "output wire signed [159:0] logit_out") using
// indexed part-selects ("+:") to read/write each 16-bit slot.
// Internal per-index signal arrays (x, fc1_raw, fc1_norm, h,
// fc2_raw) are NOT ports, so their original unpacked-array
// declarations are valid Verilog-2001 and are left unchanged.
// ============================================================

`timescale 1ns/1ps

module bitnet_mini (
    input  wire [195:0]        pixel_in,   // 196 binary pixels, LSB = pixel[0]
    output wire signed [159:0] logit_out   // 10 raw logits, flattened: logit_out[i*16 +: 16]
);

    // ── Expand packed input to individual signed wires ──
    wire signed [15:0] x [195:0];
    genvar gi;
    generate
        for (gi = 0; gi < 196; gi = gi + 1) begin : input_expand
            assign x[gi] = {15'b0, pixel_in[gi]};  // zero-extend 1-bit to 16-bit signed
        end
    endgenerate

    // ── FC1: 196→32 ternary linear ──
    wire signed [15:0] fc1_raw [31:0];
    assign fc1_raw[ 0] = 16'sd0;
    assign fc1_raw[ 1] = x[33] + x[36] + (-x[76]) + (-x[77]) + (-x[78]) + (-x[89]) + (-x[90]) + (-x[91]) + x[93] + (-x[104]) + x[106] + x[107] + x[109] + x[119] + x[120] + x[121] + x[130] + x[134] + x[143] + x[144];
    assign fc1_raw[ 2] = x[4] + x[5] + x[6] + x[7] + x[8] + x[9] + x[24] + x[25] + (-x[50]) + (-x[51]) + (-x[91]) + (-x[105]) + (-x[106]) + x[131] + x[132] + x[133] + x[134] + x[135] + (-x[157]) + (-x[159]) + (-x[160]) + (-x[161]);
    assign fc1_raw[ 3] = (-x[44]) + (-x[45]) + (-x[72]) + (-x[93]) + x[104] + x[105] + x[106] + (-x[107]) + x[119] + (-x[121]) + x[133] + (-x[149]);
    assign fc1_raw[ 4] = x[21] + (-x[45]) + (-x[46]) + (-x[60]) + (-x[61]) + x[65] + x[78] + (-x[94]) + x[102] + (-x[107]) + x[113] + x[115] + x[127] + x[128] + (-x[131]) + x[142] + (-x[145]);
    assign fc1_raw[ 5] = x[36] + x[37] + x[52] + (-x[63]) + (-x[64]) + (-x[65]) + x[67] + x[74] + (-x[76]) + (-x[77]) + (-x[78]) + (-x[79]) + (-x[80]) + x[91] + (-x[94]) + x[104] + x[105] + x[145] + x[146];
    assign fc1_raw[ 6] = x[33] + (-x[37]) + (-x[38]) + x[90] + x[106] + x[107] + x[120] + x[121] + (-x[132]) + (-x[133]) + x[141] + x[142] + (-x[146]);
    assign fc1_raw[ 7] = (-x[50]) + (-x[101]) + x[116] + x[130] + (-x[132]) + (-x[133]) + x[144] + (-x[146]) + (-x[147]) + x[157] + x[158] + (-x[160]);
    assign fc1_raw[ 8] = x[17] + x[18] + (-x[45]) + (-x[49]) + (-x[50]) + (-x[51]) + (-x[72]) + (-x[73]) + x[78] + x[91] + x[93] + x[94] + (-x[104]) + (-x[105]) + x[107] + x[108] + (-x[117]) + (-x[118]) + (-x[119]) + x[121] + x[146];
    assign fc1_raw[ 9] = (-x[44]) + x[47] + x[48] + x[49] + x[50] + x[60] + x[61] + x[64] + x[73] + x[74] + (-x[76]) + x[86] + x[87] + (-x[90]) + x[106] + (-x[129]) + (-x[130]) + (-x[134]) + (-x[142]) + (-x[143]) + (-x[144]) + (-x[145]) + (-x[146]) + (-x[147]) + (-x[148]) + x[173] + x[175] + x[176];
    assign fc1_raw[10] = x[33] + (-x[50]) + (-x[78]) + (-x[102]) + x[104] + (-x[115]) + (-x[116]) + x[117] + x[118] + (-x[122]) + (-x[128]) + (-x[129]) + x[131] + x[132] + (-x[134]) + (-x[135]) + (-x[142]) + (-x[143]) + (-x[144]) + (-x[147]) + (-x[157]) + (-x[158]) + (-x[172]);
    assign fc1_raw[11] = x[60] + x[73] + x[80] + x[86] + (-x[89]) + (-x[90]) + (-x[91]) + x[94] + x[100] + (-x[103]) + (-x[104]) + (-x[105]) + x[109] + x[114];
    assign fc1_raw[12] = (-x[21]) + (-x[22]) + x[30] + x[44] + x[45] + x[50] + x[51] + x[57] + x[64] + x[65] + x[77] + x[78] + x[79] + x[99] + x[100] + x[121] + (-x[142]) + (-x[149]) + (-x[150]) + (-x[151]) + x[173];
    assign fc1_raw[13] = x[62] + (-x[64]) + (-x[65]) + (-x[78]) + x[89] + (-x[91]) + (-x[92]) + (-x[105]) + x[117] + x[121] + (-x[146]) + (-x[147]) + x[149];
    assign fc1_raw[14] = x[63] + (-x[92]) + (-x[93]) + (-x[94]) + (-x[105]) + (-x[106]) + x[132] + x[133] + x[134] + x[135];
    assign fc1_raw[15] = 16'sd0;
    assign fc1_raw[16] = x[30] + x[38] + x[46] + x[52] + x[53] + x[67] + x[68] + (-x[76]) + (-x[90]) + (-x[107]) + (-x[109]) + x[116] + (-x[119]) + (-x[120]) + (-x[121]) + (-x[122]) + x[130] + x[131] + (-x[133]) + x[145] + x[146] + x[160] + x[161] + x[162] + x[176];
    assign fc1_raw[17] = (-x[47]) + (-x[49]) + (-x[50]) + (-x[51]) + (-x[52]) + (-x[57]) + x[88] + x[89] + x[102] + x[106] + x[109] + x[116] + x[117] + x[130] + (-x[173]) + (-x[175]);
    assign fc1_raw[18] = (-x[34]) + (-x[47]) + (-x[49]) + (-x[50]) + x[80] + x[106] + x[119] + x[120] + x[128] + x[130] + (-x[157]) + (-x[158]) + (-x[159]) + (-x[160]) + (-x[161]);
    assign fc1_raw[19] = x[49] + x[63] + x[64] + (-x[67]) + (-x[74]) + x[76] + x[77] + (-x[79]) + (-x[80]) + (-x[88]) + x[90] + (-x[92]) + (-x[93]) + (-x[94]) + (-x[106]);
    assign fc1_raw[20] = x[37] + x[45] + x[46] + x[51] + x[52] + x[53] + (-x[64]) + (-x[78]) + (-x[79]) + (-x[99]) + x[104] + x[105] + (-x[113]) + (-x[114]) + (-x[115]) + (-x[130]) + x[161];
    assign fc1_raw[21] = 16'sd0;
    assign fc1_raw[22] = (-x[87]) + (-x[88]) + (-x[101]) + (-x[102]) + x[113] + x[115] + x[117] + x[118] + (-x[120]) + x[127] + x[128] + x[130] + x[131] + (-x[133]) + (-x[134]) + (-x[146]) + (-x[147]) + (-x[161]);
    assign fc1_raw[23] = x[21] + x[32] + x[33] + x[34] + x[35] + x[36] + x[37] + x[44] + x[45] + x[46] + x[47] + (-x[62]) + (-x[76]) + (-x[87]) + (-x[88]) + (-x[89]) + (-x[94]) + (-x[102]) + x[149] + x[150];
    assign fc1_raw[24] = x[21] + (-x[45]) + (-x[46]) + (-x[76]) + (-x[77]) + (-x[90]) + (-x[92]) + x[114] + x[115] + x[116] + x[130] + x[131] + x[133] + x[145] + x[146] + (-x[172]) + (-x[173]);
    assign fc1_raw[25] = 16'sd0;
    assign fc1_raw[26] = 16'sd0;
    assign fc1_raw[27] = (-x[4]) + (-x[18]) + (-x[23]) + (-x[33]) + (-x[34]) + (-x[35]) + (-x[36]) + (-x[45]) + x[61] + x[62] + x[72] + x[73] + x[74] + x[75] + x[76] + x[80] + x[85] + x[88] + x[90] + x[91] + x[92] + x[93] + (-x[121]) + (-x[122]) + (-x[132]) + (-x[133]) + (-x[135]) + (-x[145]) + (-x[146]) + (-x[147]) + (-x[149]);
    assign fc1_raw[28] = x[25] + (-x[34]) + (-x[47]) + (-x[59]) + (-x[60]) + (-x[61]) + (-x[64]) + (-x[65]) + (-x[66]) + x[90] + x[91] + x[103] + x[104] + x[117];
    assign fc1_raw[29] = x[78] + (-x[107]) + (-x[108]) + (-x[109]) + (-x[119]) + (-x[120]) + (-x[121]) + x[130] + x[146] + x[147] + x[148] + x[149] + x[150] + x[151];
    assign fc1_raw[30] = x[5] + x[35] + (-x[62]) + (-x[63]) + (-x[76]) + (-x[90]) + (-x[100]) + (-x[102]) + (-x[103]) + (-x[114]) + (-x[115]) + (-x[116]) + (-x[117]) + x[133] + x[141] + x[142] + x[143] + x[144] + x[145] + x[158] + (-x[161]) + (-x[175]);
    assign fc1_raw[31] = x[34] + (-x[62]) + x[104] + x[105] + x[114];

    // ── RMSNorm1 ≈ arithmetic right-shift by 0 ──
    wire signed [15:0] fc1_norm [31:0];
    genvar gn1;
    generate
        for (gn1 = 0; gn1 < 32; gn1 = gn1 + 1) begin : norm1_passthru
            assign fc1_norm[gn1] = fc1_raw[gn1];
        end
    endgenerate

    // ── ReLU ──
    wire signed [15:0] h [31:0];
    genvar gr;
    generate
        for (gr = 0; gr < 32; gr = gr + 1) begin : relu
            assign h[gr] = fc1_norm[gr][15] ? 16'sd0 : fc1_norm[gr];  // h = max(0, x)
        end
    endgenerate

    // ── FC2: 32→10, 3-bit weights (shift-and-add, no multipliers) ──
    wire signed [15:0] fc2_raw [9:0];
    assign fc2_raw[0] = h[0] + (h[1] <<< 1) + -(h[2] <<< 1) + -h[4] + -h[5] + -((h[6] <<< 1) + h[6]) + -h[7] + -((h[8] <<<
                        1) + h[8]) + -((h[10] <<< 1) + h[10]) + (h[11] <<< 1) + h[11] + h[12] + -((h[13] <<< 1) + h[13]) +
                        -((h[14] <<< 1) + h[14]) + h[15] + -((h[19] <<< 1) + h[19]) + -((h[20] <<< 1) + h[20]) + h[21] +
                        h[23] + (h[24] <<< 1) + h[24] + h[25] + h[26] + -h[27] + -((h[28] <<< 1) + h[28]) + -(h[29] <<< 1) +
                        h[30];
    assign fc2_raw[1] = -h[0] + -h[1] + -((h[2] <<< 1) + h[2]) + (h[3] <<< 1) + h[3] + -h[4] + -h[5] + -h[6] + (h[7] <<< 1)
                        + h[7] + -(h[8] <<< 1) + -((h[9] <<< 1) + h[9]) + (h[10] <<< 1) + h[10] + -((h[11] <<< 1) + h[11]) +
                        h[13] + -h[15] + -h[16] + -(h[17] <<< 1) + -((h[18] <<< 1) + h[18]) + (h[19] <<< 1) + h[19] + (h[20]
                        <<< 1) + h[20] + -h[21] + h[22] + -h[23] + -((h[24] <<< 1) + h[24]) + h[25] + -h[27] + (h[28] <<< 1)
                        + -h[29] + -(h[30] <<< 1) + h[31];
    assign fc2_raw[2] = -(h[1] <<< 1) + -((h[3] <<< 1) + h[3]) + -((h[5] <<< 1) + h[5]) + -((h[6] <<< 1) + h[6]) + -(h[8]
                        <<< 1) + -(h[9] <<< 1) + h[10] + -h[11] + (h[12] <<< 1) + (h[13] <<< 1) + h[13] + (h[14] <<< 1) +
                        h[14] + (h[15] <<< 1) + (h[16] <<< 1) + h[16] + -((h[17] <<< 1) + h[17]) + (h[18] <<< 1) + (h[19]
                        <<< 1) + -h[21] + -((h[22] <<< 1) + h[22]) + (h[23] <<< 1) + -(h[24] <<< 1) + -h[25] + -h[26] +
                        (h[27] <<< 1) + h[27] + -((h[28] <<< 1) + h[28]) + (h[29] <<< 1) + h[29] + -h[30] + -((h[31] <<< 1)
                        + h[31]);
    assign fc2_raw[3] = -(h[1] <<< 1) + h[2] + -h[4] + (h[5] <<< 1) + h[5] + -((h[6] <<< 1) + h[6]) + -(h[8] <<< 1) + h[10]
                        + -((h[11] <<< 1) + h[11]) + -(h[12] <<< 1) + -((h[13] <<< 1) + h[13]) + h[15] + (h[16] <<< 1) +
                        h[17] + -h[18] + -(h[19] <<< 1) + (h[20] <<< 1) + -h[22] + (h[23] <<< 1) + -h[24] + h[25] + -h[26] +
                        -h[27] + -h[28] + (h[29] <<< 1) + h[29] + -h[30] + h[31];
    assign fc2_raw[4] = h[0] + -h[1] + -((h[2] <<< 1) + h[2]) + h[3] + h[4] + (h[6] <<< 1) + h[6] + (h[7] <<< 1) + h[7] +
                        (h[8] <<< 1) + -(h[9] <<< 1) + (h[10] <<< 1) + h[11] + -h[12] + h[13] + -((h[14] <<< 1) + h[14]) +
                        -h[15] + -((h[16] <<< 1) + h[16]) + (h[17] <<< 1) + h[17] + h[18] + -(h[19] <<< 1) + -(h[20] <<< 1)
                        + h[21] + -((h[22] <<< 1) + h[22]) + -((h[23] <<< 1) + h[23]) + -(h[24] <<< 1) + -h[25] + -h[26] +
                        (h[27] <<< 1) + (h[28] <<< 1) + h[28] + -((h[29] <<< 1) + h[29]) + -(h[30] <<< 1) + -h[31];
    assign fc2_raw[5] = h[1] + (h[3] <<< 1) + -h[4] + (h[5] <<< 1) + h[5] + h[6] + -((h[7] <<< 1) + h[7]) + (h[8] <<< 1) +
                        -((h[10] <<< 1) + h[10]) + -((h[11] <<< 1) + h[11]) + -(h[13] <<< 1) + h[15] + -(h[16] <<< 1) +
                        -((h[17] <<< 1) + h[17]) + (h[18] <<< 1) + h[18] + -((h[19] <<< 1) + h[19]) + (h[20] <<< 1) + h[20]
                        + h[21] + (h[22] <<< 1) + h[22] + (h[23] <<< 1) + -h[24] + -h[25] + -h[27] + -((h[28] <<< 1) +
                        h[28]) + -h[29] + (h[30] <<< 1) + h[30] + -h[31];
    assign fc2_raw[6] = h[0] + -(h[1] <<< 1) + -((h[2] <<< 1) + h[2]) + (h[3] <<< 1) + -((h[4] <<< 1) + h[4]) + -((h[5] <<<
                        1) + h[5]) + -((h[7] <<< 1) + h[7]) + -h[8] + (h[9] <<< 1) + h[9] + -(h[10] <<< 1) + h[11] + (h[12]
                        <<< 1) + h[12] + (h[13] <<< 1) + h[13] + -((h[14] <<< 1) + h[14]) + -h[15] + -((h[16] <<< 1) +
                        h[16]) + -((h[17] <<< 1) + h[17]) + -((h[18] <<< 1) + h[18]) + -h[20] + -h[21] + -((h[24] <<< 1) +
                        h[24]) + -h[26] + (h[27] <<< 1) + -((h[28] <<< 1) + h[28]) + -((h[29] <<< 1) + h[29]) + (h[30] <<<
                        1) + -h[31];
    assign fc2_raw[7] = -h[0] + (h[1] <<< 1) + h[1] + (h[2] <<< 1) + -(h[3] <<< 1) + -h[4] + -(h[5] <<< 1) + -h[7] + -((h[8]
                        <<< 1) + h[8]) + h[10] + -((h[12] <<< 1) + h[12]) + (h[13] <<< 1) + h[13] + (h[14] <<< 1) + h[14] +
                        -h[16] + (h[17] <<< 1) + (h[18] <<< 1) + h[19] + -((h[20] <<< 1) + h[20]) + -h[22] + -((h[23] <<< 1)
                        + h[23]) + h[24] + -h[25] + h[26] + -h[27] + (h[28] <<< 1) + (h[29] <<< 1) + h[29] + -((h[30] <<< 1)
                        + h[30]) + -h[31];
    assign fc2_raw[8] = -((h[1] <<< 1) + h[1]) + -(h[2] <<< 1) + (h[3] <<< 1) + (h[4] <<< 1) + h[4] + -h[5] + (h[6] <<< 1) +
                        -h[7] + -h[8] + -((h[9] <<< 1) + h[9]) + -h[10] + -((h[11] <<< 1) + h[11]) + h[12] + -h[13] + -h[15]
                        + -h[16] + h[17] + -h[18] + h[19] + -h[21] + -h[22] + (h[23] <<< 1) + h[24] + h[25] + h[26] +
                        -((h[27] <<< 1) + h[27]) + -((h[28] <<< 1) + h[28]) + -h[29] + -h[30] + (h[31] <<< 1) + h[31];
    assign fc2_raw[9] = h[0] + -(h[1] <<< 1) + h[2] + -((h[4] <<< 1) + h[4]) + (h[5] <<< 1) + -(h[7] <<< 1) + (h[8] <<< 1) +
                        h[8] + -((h[9] <<< 1) + h[9]) + h[11] + -(h[13] <<< 1) + -h[14] + -h[15] + -(h[16] <<< 1) + (h[17]
                        <<< 1) + h[17] + (h[18] <<< 1) + -(h[19] <<< 1) + h[20] + h[21] + -(h[22] <<< 1) + -((h[23] <<< 1) +
                        h[23]) + (h[24] <<< 1) + -h[25] + -((h[27] <<< 1) + h[27]) + (h[28] <<< 1) + h[28] + -((h[29] <<< 1)
                        + h[29]) + -((h[30] <<< 1) + h[30]);

    // ── RMSNorm2 ≈ arithmetic right-shift by 0 ──
    // logit_out is a flattened packed bus; each 16-bit logit i lives at
    // bit offset i*16 (indexed part-select, Verilog-2001 legal).
    genvar gn2;
    generate
        for (gn2 = 0; gn2 < 10; gn2 = gn2 + 1) begin : norm2_shift
            assign logit_out[gn2*16 +: 16] = fc2_raw[gn2];
        end
    endgenerate

endmodule

// ============================================================
// Argmax: finds the digit with highest logit
// ============================================================
module argmax10 (
    input  wire signed [159:0] logit_in,   // 10 × 16-bit logits, flattened: logit_in[i*16 +: 16]
    output reg  [3:0]          digit_out   // 0-9
);
    integer i;
    reg signed [15:0] max_val;
    always @(*) begin
        max_val   = logit_in[0 +: 16];
        digit_out = 4'd0;
        for (i = 1; i < 10; i = i + 1) begin
            if ($signed(logit_in[i*16 +: 16]) > max_val) begin
                max_val   = logit_in[i*16 +: 16];
                digit_out = i[3:0];
            end
        end
    end
endmodule

// ============================================================
// Top wrapper: pixels in → digit out
// ============================================================
module bitnet_mini_top (
    input  wire [195:0] pixel_in,
    output wire [3:0]   digit_out
);
    wire signed [159:0] logits_flat;
    bitnet_mini  nn  (.pixel_in(pixel_in), .logit_out(logits_flat));
    argmax10     ax  (.logit_in(logits_flat), .digit_out(digit_out));
endmodule


// ============================================================
// Top wrapper: combinational to timed
// ============================================================
module digit_classifier (
    input  wire         clk,
    input  wire         rst_n,
    input  wire         start,
    input  wire [195:0] image_in,
    output reg  [3:0]   digit_out,
    output reg          valid_out
);
    wire [3:0] nn_digit;

    // Instantiate the generated BitNetMini
    bitnet_mini_top nn (
        .pixel_in  (image_in),
        .digit_out (nn_digit)
    );

    reg valid_pipe;

    always @(posedge clk) begin
        if (!rst_n) begin
            digit_out  <= 4'd0;
            valid_pipe <= 1'b0;
            valid_out  <= 1'b0;
        end else begin
            valid_pipe <= 1'b0;  // default
            valid_out  <= valid_pipe;

            if (start) begin
                $display("image_array=%b", image_in);
                $display("image_array_int=%d", image_in);
                $display("nn_digit=%d", nn_digit);
                digit_out  <= nn_digit;  // cycle N:   data latched
                valid_pipe <= 1'b1;      // cycle N+1: valid_out goes high
            end                          // cycle N+1: top reads digit_out — it's stable
        end
    end


endmodule